/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { 
  StyleSheet, 
  Text, 
  View, 
  TextInput,
  TouchableOpacity 
} from 'react-native';
import RNPagecall from 'react-native-pagecall';

export default class App extends Component {
  state = {
    serverURL: "https://pplink.net",
    roomID: "class101_test_peter_0517"
  };

  handleURL = text => {
    this.setState({ serverURL: text });
  };
 
  handleRoomID = text => {
    this.setState({ roomID: text });
  };

  startLiveStreaming = (serverURL, roomID) => {
    RNPagecall.startLiveStreamingWithURL(serverURL, false, roomID, "","");
  };

  componentDidMount() {
    
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Live Streaming Example</Text>
        <TextInput
          style={styles.input}
          underlineColorAndroid="transparent"
          placeholder="URL"
          placeholderTextColor="#9a73ef"
          autoCapitalize="none"
          onChangeText={this.handleURL}
        />
        <TextInput
          style={styles.input}
          underlineColorAndroid="transparent"
          placeholder="RoomID"
          placeholderTextColor="#9a73ef"
          autoCapitalize="none"
          onChangeText={this.handleRoomID}
        />
        <TouchableOpacity
          style={styles.submitButton}
          onPress={() => this.startLiveStreaming(this.state.serverURL, this.state.roomID)}
        >
          <Text style={styles.submitButtonText}>Start!!</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    //alignItems: 'center',
    backgroundColor: '#F5FCFF',
    paddingTop: 30
  },
  title: {
    fontSize: 20,
    textAlign: 'left',
    margin: 15,
  },
  input: {
    margin: 15,
    height: 40,
    borderColor: "#7a42f4",
    borderWidth: 1
  },
  submitButton: {
    backgroundColor: "#7a42f4",
    padding: 10,
    margin: 15,
    height: 40
  },
  submitButtonText: {
    color: "white"
  }
});
